### ISSUE TITLE
Name or service not known

### ISSUE THREAD

**Issue by yanickvanbarneveld** [dmartinpro/RFLinkGateway#3]
Hi,

I installed RFLinkGateway in "/etc/openhab2/oh2-scripts" and ran the command "sudo python /etc/openhab2/oh2-scripts/RFLinkGateway.py &". It finds the config file but I am retrieving this error, am I missing something?

`2017-09-07 09:45:23,586 - RFLinkGW.SerialProcessing - __init__ - INFO - Starting...
2017-09-07 09:45:23,588 - RFLinkGW.SerialProcessing - connect - INFO - Connecting to serial
2017-09-07 09:45:23,590 - RFLinkGW.SerialProcessing - __init__ - INFO - Ignoring devices: [u'Friedland', u'Oregon Temp/FD10', u'BL999', u'RTS']
2017-09-07 09:45:23,594 - RFLinkGW.MQTTClient - __init__ - INFO - Starting...
2017-09-07 09:45:23,598 - RFLinkGW.MQTTClient - __init__ - INFO - Connection with credentials (user: user).
Traceback (most recent call last):
  File "/etc/openhab2/oh2-scripts/RFLinkGateway.py", line 78, in <module>
    main()
  File "/etc/openhab2/oh2-scripts/RFLinkGateway.py", line 65, in main
    mqtt = MQTTClient.MQTTClient(messageQ, commandQ, config)
  File "/etc/openhab2/oh2-scripts/MQTTClient.py", line 29, in __init__
    self._mqttConn.connect(config['mqtt_host'], port=config['mqtt_port'], keepalive=120)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 760, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 887, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known
`

Like to hear from you.

**Comment by dmartinpro** [comment]
Are you sure the config file is correctly set up?
Did you specify the correct values for mqtt host, user/pwd?

**Comment by dmartinpro** [comment]
Since I didn't have any answer, I'm considering this issue as solved.
