### ISSUE TITLE
Error in Processors.py - can't start RFLinkGateway

### ISSUE THREAD

**Issue by kkmaslowski** [dmartinpro/RFLinkGateway#7]
Hi.
When I try to start RFLinkGateway.py I have error:

```
# python RFLinkGateway.py 
Traceback (most recent call last):
  File "RFLinkGateway.py", line 13, in <module>
    import SerialProcess
  File "/opt/RFLinkGateway/SerialProcess.py", line 7, in <module>
    import Processors
  File "/opt/RFLinkGateway/Processors.py", line 23, in <module>
    range(0,3): 'LOW',
TypeError: unhashable type: 'list'
```

System info:
Raspbian 9.4
Python 2.7.13

**Comment by dmartinpro** [comment]
Right, I should have mentioned: the project is now Python 3 only.
I've added this to the README file.
